add controller
Ivnsol/java-shareit pull request #2
Opened 2024-02-24 12:05 UTC by Ivnsol

2024-02-24 17:53 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2024-02-24 17:53 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public static ItemDto fromItemToItemDto(Item item) {
Так, в принципе, тоже можно, однако обычно делают специальные объекты-мапперы, которые преобразуют сущности в dto и обратно. О них в ТЗ упомянуто. Наверное с маппером разделение обязанностей между объектами будет более четкое :)

2024-02-24 17:53 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long id;
С этой аннотацией надо поаккурантей. Она генерирует equals и hashCode на основании всех полей. 
Однако, сущность - это не просто объект, это представление строки таблицы базы данных, а строку таблицы однозначно определяет ее идентификатор, и потому, соотвественно, для сущностей equals и hashCode стоит определять на основе id (первичного ключа). 

Остальные поля, при этом, могут вообще быть разными, то есть могут существовать разные версии одного и того же объекта, но как это разруливатеся - это уже отдельная история.
 
Плюс еще некоторые поля могут быть ленивыми коллекциями и в момент обращения будут генерироваться sql-запросы, которые и не нужны в данный момент

Т.е. лучше или переопределить руками или указать через аннотации как генерировать эти методы :)


А вот для DTO такая аннотация в самый раз

2024-02-24 17:53 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public static final List<Item> items = new CopyOnWriteArrayList<>();
static тут не нужен, пусть это будет полем класса :)

CopyOnWriteArrayList
Что то  не уверен что стоит именно в нем хранить на постоянно основе наши сущности. Давай все таки сделаем обычный список, CopyOnWrite лучше использовать точечно, он память неплохо так расходует. Пока предположим что мы потом сделаем нормальную синхронизацию :)

2024-02-24 17:53 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                items.remove(item);
Удалять из списка лучше через итератор 
Иначе мы можем получить NPE или ошибку о конкурентной модификации списка в ряде случаев :)
Из за того что мы передираем элементы в цикле for-each и меняем коллекцию по которой итерируемся

2024-02-24 17:53 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    @SneakyThrows
@SneakyThrows

Эту аннотацию лучше не использовать, мы так прячем ошибки и никто потом не поймет почему ничего не работает хотя визуально все ок, это как чек-энджин изолентой заклеить :)

2024-02-25 11:39 UTC, Ivnsol commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public static final List<Item> items = new CopyOnWriteArrayList<>();
Static убрал, почему-то гит ругается при добавление простого ArrayList, если в дальнейшем подключим БД, то CopyOnWriteArrayList в качестве временного решения.

2024-02-25 16:06 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо 

Смотрю используется map-struct, это достаточно популярное решение :)

2024-02-25 16:06 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    public static final List<User> USERS = Collections.synchronizedList(new ArrayList<>());
Ок, пусть будет синхронизованная коллекция :)
А так, CopyWrite копирует себя каждый раз, расход памяти был бы высоковат

2024-02-26 06:09 UTC, merged