add booking
Ivnsol/java-shareit pull request #3
Opened 2024-03-18 16:50 UTC by Ivnsol

2024-03-19 10:13 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

Вообще, СУБД - часто узкое место, потому лучше делать меньше запросов и не таскать лишние данные, а то ОЗУ не хватит :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/GlobalExceptionHandler.java
> +        response.put("error", "The user has not booked anything");
Можно и не описывать конкретику в глобальном обработчике :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @ExceptionHandler(IllegalArgumentException.class)
А не получится эти хендлеры вынести в отдельный класс, просто чтобы не мешались в контроллере :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingCastomMapper.java
> +        bookingDto.setItem(itemMapper.itemDtoFromItem(itemRepository.getById(booking.getItemId())));
Djn Вот это может быть опасно с точки зрения производительности, тут лучше маппить то, что пришло в самом объекте в этих полях (item, booker) чем идти в БД и тащить эти записи дополнительно. Вдруг кто то решит этот маппер использовать при обработке целой коллекции объектов - получит кучу запросов в БД, что совсем не эффективно и просадит наше приложение, пусть внешний код сам подкладывает данные, а тут лишь обработаем то что есть :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST);
Тут наверно лучше вернуть boolean чем кидать исключение, так будет гибче, все равно внешний код дергает этот метод, пусть он и решает кидать исключение или делать что то другое :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Incorrect ID of owner");
По идее сервис ничего не знает о среде которая его вызывает, и там не всегда http (может быть брокер сообщений и тд). По тому тут кидать исключения связанные с кодами http не стоит, смешиваем обязанности слоев. Тут лучше бросить свое исключение, а вот связать его с кодами HTTP можно в controllerAdvice :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new RuntimeException(e);
Как то сурово тут бросать RuntimeException, давай сделаем какое то свое, конкретное :)

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        List<Booking> bookings = bookingStorage.findAll();
Там может быть очень много записей, давай лучше сделаем свой запрос на каждый случай ....

2024-03-19 10:13 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            .filter(o -> o.getEnd().isAfter(LocalDateTime.now()))
.... отдельный запрос,  в котором будем фильтровать и сортировать так как нам надо но на стороне СУБД, так гораздо эффективней :)

2024-03-19 17:43 UTC, EugeneLenkevich requested changes
Давай все таки N+1 уберем, отметил комментарием :)

2024-03-19 17:43 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        itemMapper.itemDtoFromItem(itemRepository.getById(booking.getItemId())),
Все таки немного не то, тут у нас опять идет куча запросов в БД, лучше конечно такого избегать, это и называется проблема N+1 запроса :)


Давай связи с сущностями нормально пропишем, примерно вот так, с типом EAGER, тогда не надо будет руками их подгружать, JPA само нам все загрузит одним запросом
![image](https://github.com/Ivnsol/java-shareit/assets/109306643/37f1c837-d9c8-43f5-800e-327188a532a0)



====


А для коллекций решается подобное с помощью помощью join fetch

![image](https://user-images.githubusercontent.com/94845100/194059305-413c94fd-e9da-40d1-8090-05568e0cc255.png)


https://stackoverflow.com/questions/17431312/what-is-the-difference-between-join-and-join-fetch-when-using-jpa-and-hibernate


Или еще вот, entity graph
https://sysout.ru/entity-graph-v-spring-data-jpa/

2024-03-20 08:44 UTC, Ivnsol commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        itemMapper.itemDtoFromItem(itemRepository.getById(booking.getItemId())),
добавил интерфейс и новую модель, что бы избежать n+1

2024-03-20 12:54 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-03-21 10:48 UTC, merged