add test&request
Ivnsol/java-shareit pull request #4
Opened 2024-03-25 11:50 UTC by Ivnsol

2024-03-26 15:23 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

В целом все гут, и если для имен методов указакн запрос явно, то можно попроще называть :)

2024-03-26 15:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0) {
Это вроде аннотацией @Min можно сделать или не? :)

2024-03-26 15:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingStorage.java
>      List<Booking> findAllWhereItemIdIsOrderByEndDesc(List<Long> itemsId);
Запрос задан через @Query, можно метод и попроще и поудобней назвать, так в длинном имен нет надобности :)

2024-03-26 15:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingStorageForList.java
> +    List<AllBookingsAsList> findAllByBookerOrderByEndDesc(@Param("owner") Long owner, Pageable pageRequest);
ORDER BY b.start DESC

В объекте Pageable уже есть возможность задать сортировку, попробуй, может получится указать через него,  т.е. не прибивать ее гвоздями указывая в самом запросе? :)

2024-03-26 15:23 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>                  case ALL:
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<State, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<State, Supplier> handlers = ...
handlers.put(ALL, this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2024-03-27 10:27 UTC, Ivnsol commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0) {
почему-то не проходит и @min и @positive (@Valid так же был)

2024-03-27 11:02 UTC, Ivnsol commented on src/main/java/ru/practicum/shareit/booking/repository/BookingStorageForList.java
> +    List<AllBookingsAsList> findAllByBookerOrderByEndDesc(@Param("owner") Long owner, Pageable pageRequest);
Круто, получилось, мне так тоже больше нравится, а сортировка происходит при запросе в бд? или уже с коллекцией?

2024-03-27 13:46 UTC, Ivnsol commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>                  case ALL:
я ознакомился с материалом, лечу по срокам, возьму сделать как ДЗ когда будет чуть посвободнее

2024-03-27 14:36 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (from < 0) {
не критично

2024-03-27 14:37 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/repository/BookingStorageForList.java
> +    List<AllBookingsAsList> findAllByBookerOrderByEndDesc(@Param("owner") Long owner, Pageable pageRequest);
На стороне БД. JPA генерирует sql-запрос на основе описания метода, так мы делаем по сути дела динамическую сортировку :)

2024-03-27 14:38 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-03-27 14:54 UTC, merged