Add docker
Ivnsol/java-shareit pull request #5
Opened 2024-04-04 11:10 UTC by Ivnsol

2024-04-04 13:15 UTC, EugeneLenkevich requested changes
Привет, Иван! Спасибо за PR.

Все хорошо, докер на месте, модули, связей между ними минимум. Предложу только одно улучшение опциональное, если нет времени то отправляй обратно как есть :)

2024-04-04 13:15 UTC, EugeneLenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        super(
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2024-04-07 08:20 UTC, Ivnsol commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        super(
Обязательно посмотрю чуть попозже, можем пока принять эту версию ?🙂

2024-04-07 10:11 UTC, EugeneLenkevich approved these changes
Поехали тогда дальше  :)

2025-02-13 14:32 UTC, closed without merging